# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUsjb52b2beSYaOfX7KyLs9UFkBCgCLK

#Lista de exercicios 1

Questão 1:
"""

altura = float(input('informe sua altura: '))
sexo = input('informe seu sexo M | F: ')
peso = float(input('informe seu peso: '))

if sexo != 'f':
  calculo = (72.7*altura)-58

else:
  calculo = (62.1*altura) - 44.7


if peso == calculo:
  print(f'Você esta dentro do peso ideal! ideal -> {calculo}, atual -> {peso}')
elif peso > calculo:
  print(f'Você esta acima do peso ideal! ideal -> {calculo}, atual -> {peso }')
else:
  print(f'Você esta abaixo do peso idela! ideal -> {calculo}, atual -> {peso}')

"""Questao 2:"""

download = float(input('Informe o tamanho do arquivo (MB): '))
velocidade = float(input('Informe a velocidade da sua internet: '))

calculo = round(download / (velocidade/8),1)

print(f'um arquivo de {download} MB, baixado a {velocidade} Mbps, leva em torno de {calculo} minutos')

"""Questão 3:"""

lista=[]

numero = int(input('Digite um numero: '))
n2 = int(input('Digite o segundo numero: '))
n3 = int(input('Digite o terceiro numero: '))

lista = [numero, n2, n3]
print (lista)
lista.sort()
print(lista)
lista.reverse()
print(lista)

"""Questão 4:"""

resposta = input('Informe o turno que você estuda Matutino | Vespertino | Noturno: ')

if resposta == "matutino":
  print('Bom Dia!')
elif resposta == 'vespertino':
  print('Boa Tarde')
elif resposta == 'noturno':
  print('Boa Noite')
else:
  print('Valor inválido')

"""Questão 5:"""

numero = int(input('Digite um numero: '))

if numero %2 == 0:
  print('par')
else:
  print('impar')

"""Questão 6:"""

#fazer um loop e ir comparando os valores informados e armazenando o maior valor
x=0
maior_numero = 0
while(x != 5):

  n = int(input('informe um numero: '))

  if(n> maior_numero):
    maior_numero = n
  x+=1

print(f'O maior numero foi {maior_numero}')

"""Questão 7:"""

nota1 = int(input("informe as nota 1: "))
nota2 = int(input("informe as nota 2: "))
nota3 = int(input("informe as nota 3: "))
nota4 = int(input("informe as nota 4: "))
nota5 = int(input("informe as nota 5: "))

soma = nota1 + nota2 + nota3 + nota4 + nota5

print('A soma das notas é ' ,soma)

media = soma / 5
print(f'Média do Aluno foi de {media}')

"""Questão 8:"""

x=0
while(x!=50):

  if(x%2 !=0):
    print(x)

  x+=1

"""Questão 9:"""

lista_numeros = [1.7,2.5,3.55,7,99,63.57,11,25,9,99,150.75]

lista_numeros.reverse()
print(lista_numeros)

"""Questão 10:"""

x=0
lista_n = []

while(x!=-1):
  x = int(input('informe sua nota: '))
  if(x!=-1):
    lista_n.append(x)

tamanho = len(lista_n)
print('quantidade:' ,tamanho)

print(lista_n)

lista_n.reverse()
for itens in lista_n:
  print(itens)

